### ISSUE TITLE
[Feature request] Support sameSite attribute

### ISSUE THREAD

**Issue by nihakue** [bouzuya/cookie-storage#10]
Hi, is there any reason why this library couldn't support the sameSite attribute on cookies? Actually, is there any reason why this library couldn't support setting arbitrary attributes on cookies? I see that at the moment it's limited to the fields in CookieOptions, but I can't think of a reason why you wouldn't want to allow any attribute (future proof).

Happy to create a PR for this.

**Comment by bouzuya** [comment]
#11
