### ISSUE TITLE
SameSite Attribute to None

### ISSUE THREAD

**Issue by Daver2910** [bouzuya/cookie-storage#201]
Hey guys,

We are using this package in an e-commerce app. We use oidc as auth and several external payment providers.

The issue we have is, we need to set the samesite attribute to 'None' so that we have the auth cookie on the way back from the payment providers.

is this possible?

**Comment by bouzuya** [comment]
I added SameSite=None support in v6.1.0.

https://github.com/bouzuya/cookie-storage/commit/c4c00f27654a9a135f4327a718908a104f2b0498
