### ISSUE TITLE
UglifyJS Error when running bundle command  

### ISSUE THREAD

**Issue by 007FR** [bouzuya/cookie-storage#21]
Hello Cookie_Storage developer(s),

When I run the following bundle command  
**gulp bundle --ship**

**I receive the error below: Note- My solution is named drop-down-banner** 

[17:37:21] Error - [webpack] 'dist':
drop-down-banner-application-customizer.js from UglifyJs
Unexpected token: operator (>) [drop-down-banner-application-customizer.js:13194,25]

I narrowed it down to this command.  As soon as I comment it out, I am able to bundle my solution properly. I tried a few variations to initialize, but still no resolution.
 **var cookiesStorage = new CookieStorage();**

Your cookie storage solution is the simplest/cleanest solution that I have seen out there. If you are able to resolve this bug, it is appreciated.

**Comment by bouzuya** [comment]
refs: https://stackoverflow.com/questions/43888474/unexpected-token-operator-from-uglifyjs

I removed support for node.js v6 at v5.0.0. And UglifyJS doesn't support es6.

Perhaps these caused errors in using uglifyjs.
I will try to change the setting of preset-env later.  I think that will probably fix it.

**Comment by 007FR** [comment]
That would perfect! Let me know once you get that changed and I can test it out.

**Comment by bouzuya** [comment]
https://github.com/bouzuya/cookie-storage/releases/tag/v5.0.3

**Comment by 007FR** [comment]
The updated code worked like a charm. Thanks again!
