### ISSUE TITLE
Storage interface in this project differs from typescript Storage interface

### ISSUE THREAD

**Issue by astegmaier** [bouzuya/cookie-storage#5]
First of all, I wanted to say thanks for creating this project and contributing it--I'm finding it quite useful!

I'm running into trouble when trying to pass Cookie storage to another library ([angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc)) that expects an implementation of the typescript Storage interface. I get the following error:
```
TS2322: Type 'CookieStorage' is not assignable to type 'Storage'.
        Index signature is missing in type 'CookieStorage'.
```
I took a look, and it seems that the Storage interface included in the cookie storage project (in [storage.ts](https://github.com/bouzuya/cookie-storage/blob/master/src/storage.ts)) differs slightly from the one defined by typescript's lib.dom.d.ts in [these lines](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L11497-L11498):
```
    [key: string]: any;
    [index: number]: string;
```
I tried adding them to CookieStorage's type definition and it seemed to fix the problem. Reading up on "indexable types" in the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/interfaces.html), it was unclear to me whether adding these two lines to CookieStorage's storage.ts would be enough, or whether additional modifications to the CookieStorage class would be necessary to provide robust support.

Would you be open to a pull request along these lines? (I'm happy to prepare one, but I wanted to check first). Are there any other considerations I should take into account? Or maybe there is another approach I could take to accomplish my goals?

Thanks!
Andrew

**Comment by bouzuya** [comment]
Thank you for your comment. Welcome your PR!

I think it would be better to add it to `CookieStorage` for compatibility and convinience.

But I think it would not be better to add it to `Storage`. `Storage` interface is based on WHATWG Storage. I recommend to use the Web Storage API (`setItem`, `getItem`, `removeItem`, `key`, `length`) .
https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface

**Comment by astegmaier** [comment]
Awesome. I went ahead and submitted PR #6 

I was considered whether or not to try to implement some additional code so that you could use these string and number accessors (e.g. myCookieStorage["myKey"] = "myValue") to get and set actual cookies instead of just properties on the cookieStorage object. It looked like this _might_ be possible using a Proxy object (see example [here](http://stackoverflow.com/questions/1711357/how-would-you-overload-the-operator-in-javascript)), it seemed that this would introduce a dependency on ES6 that could not be easily worked around with transpiling (see [here](http://stackoverflow.com/questions/24940716/overload-for-typescript-class)), so I decided against it. I'm open to suggestions however if you think there's another way to do this, or if you think I made the wrong call.

**Comment by bouzuya** [comment]
hmm... I forgot that the indexer (`[]`) could not be implemented easily...

**Comment by astegmaier** [comment]
I'm working on a potential implementation now in my fork. It definitely involves the Proxy object, but after looking at the [support matrix](https://kangax.github.io/compat-table/es6/#test-Proxy) for that, I think it might still be useful to most folks, since the support is pretty robust across modern browsers. The design goal would be to help make CookieStorage a drop-in replacement for localStorage and sessionStorage, both of which support indexing (e.g. localStorage["myKey"] = myValue). It's not a small change, but I think it could prove useful to other folks, and it is necessary in my case, since the library to which I want to supply CookieStorage uses these indexing techniques. I'll keep you posted on my progress, and I'd definitely appreciate any feedback.

**Comment by astegmaier** [comment]
I think PR #7 looks good from my side. Do you have any feedback, suggestions, or ideas about how to improve it?

**Comment by astegmaier** [comment]
Thanks for accepting the PR! Hopefully other folks will find it useful.

Did you have any plans about when to do the next release? I'd like to use the indexing feature in my project, and it would be great to be able to include it via public npm (for CI on a service) instead of needing to manually install from source.

**Comment by bouzuya** [comment]
I want to release it as v3 in a few days.

I have made some broken changes. See: 
https://github.com/bouzuya/cookie-storage/commit/1579e053fdee1431cbc34b0f861e1ba220e82fd3

I'm sorry I delete `ProxyIsSupported`.  I think, at runtime, the user should not change the calling method with and without Proxy. It is dangerous. It is better to use it only when the proxy is guaranteed.

**Comment by astegmaier** [comment]
Awesome! Removing `ProxyIsSupported` and replacing it with an undefined check does seem simpler and more elegant--I like it.

Just curious--why did you choose to remove Node 5 support? It's doesn't seem important, but in my tests, it appears to work fine still with the latest code. Was it just to save testing time, since testing node 4 should cover it?

**Comment by bouzuya** [comment]
https://github.com/nodejs/LTS

**Comment by bouzuya** [comment]
v3 release
https://github.com/bouzuya/cookie-storage/releases/tag/3.0.0
