### ISSUE TITLE
ES5 compatibility

### ISSUE THREAD

**Issue by xduseko** [bouzuya/cookie-storage#68]
Is there a reason to use Object.assign? It's not ES5 compatible.

Would you consider replacing
```
this._defaultOptions = Object.assign({
    domain: null,
    expires: null,
    path: null,
    secure: false
}, defaultOptions);
```

with something like that?
```
this._defaultOptions = { ...{
    domain: null,
    expires: null,
    path: null,
    secure: false
}, ...defaultOptions };
```

Typescript can handle it well if you set target to ES5.

**Comment by bouzuya** [comment]
Thank you for your comment. But I don't set to target ES5. Object.assign can be used in most environments. You can use polyfill if you want.

https://github.com/bouzuya/cookie-storage/blob/e544027301bd6418eeef81af01848c2617e8e7c8/package.json#L13-L19
